# Generated by Django 4.1.7 on 2023-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_mood',
            field=models.CharField(blank=True, default='happy', max_length=20),
        ),
    ]
