# Generated by Django 4.1.7 on 2023-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
