# Generated by Django 4.1.7 on 2023-04-29 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('movieId', models.IntegerField(blank=True)),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('language', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.CharField(max_length=5)),
                ('imdbVotes', models.CharField(max_length=10)),
                ('imdbRating', models.FloatField()),
                ('imdbID', models.CharField(max_length=10)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
