# Generated by Django 4.1.7 on 2023-04-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesrating',
            old_name='tag',
            new_name='tags',
        ),
    ]
