# Generated by Django 4.1.7 on 2023-04-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movieid_movie_movieid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesrating',
            old_name='tags',
            new_name='tag',
        ),
    ]
