# Generated by Django 4.1.7 on 2023-05-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_boxoffice_movie_rated_movie_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='timestamp',
        ),
    ]
