# Generated by Django 4.1.7 on 2023-04-20 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_rename_tags_moviesrating_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviesRating',
            new_name='MoviesRatings',
        ),
        migrations.RenameField(
            model_name='moviesratings',
            old_name='ratings',
            new_name='rating',
        ),
    ]
