# Generated by Django 4.1.7 on 2023-04-21 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_rename_moviesrating_moviesratings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviesRatings',
            new_name='MoviesRating',
        ),
        migrations.RenameField(
            model_name='moviesrating',
            old_name='tag',
            new_name='tags',
        ),
    ]
