# Generated by Django 4.1.7 on 2023-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_moviesratings_moviesrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
