# Generated by Django 4.1.7 on 2023-04-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesrating',
            name='tags',
        ),
    ]
